storage:
  raw: "./data/raw"
  translated: "./data/translated"

download:
  timeout: 20
  retries: 3
  delay: 1.0
  concurrency: 3

sources:
  mangadex:
    translated_languages:
      - en
      - ja
      - ko
      - zh
      - zh-hk
    data_saver: false

translation:
  translator: "deepseek"
  target_language: "VIN"

  font_path: "./fonts/Arial-Unicode-Regular.ttf"
  renderer: "manga2eng"
  alignment: "center"
  direction: "horizontal"

  uppercase: true
  font_size_offset: 1
  font_size_minimum: 16
  no_hyphenation: true
  line_spacing: 0.01
  disable_font_border: true

database:
  path: "./data/state.db"
